### ISSUE TITLE
npm http-server 모듈 실행시 /dist/ 접근하는 오류

### ISSUE THREAD

**Issue by erados** [logico-philosophical/math-o-matic#60]
[2020-11-10T07:07:45.493Z]  "GET /erados/math-o-matic/dist/math.min.js" Error (404): "Not found"

<img src="https://i.imgur.com/1HU62j1.png" width="500px"/>

**Comment by logico-philosophical** [comment]
***It's not a bug, it's a feature.***

[CONTRIBUTING.md](https://github.com/logico-philosophical/math-o-matic/blob/master/CONTRIBUTING.md)을 참조하여 개발 환경을 올바로 구축하세요.
