### ISSUE TITLE
파싱 오류

### ISSUE THREAD

**Issue by erados** [logico-philosophical/math-o-matic#79]
```
schema subset_is_subgroup($G$ cls g, $H$ cls h, $\cdot$ cls f) {
	is_group(g, f),
	subseteq(h, g),
	is_bin_op(rel_restrict(f, cartesian(h, h)), h),
	in(identity_element(g, f), h),
	Uin(h, (cls a) => {in(inverse_element(a, g, f), h)}) |- 
		N(bin_op_associative(rel_restrict(f, cartesian(h, h)), h)) |-
			NU_to_XN[@h6]
}
```
의 출력 7번째 라인에서 x 의 자리가 z 로 채워짐.

<img src="https://user-images.githubusercontent.com/19205043/100517876-60fc3780-31d1-11eb-8fd7-962ed93ee2cb.png" width="500">

**Comment by logico-philosophical** [comment]
일단 이것은 파싱 오류가 아니다. 7번째 열에서 제일 바깥의 변수가 `bin_op_associative`의 정의에서처럼 `x`가 되지 않고 `z`가 된 것은 `NU_to_XN[@h6]`의 결과가 `NU_to_XN`의 우변에서 `f`를 추정된 인자로 치환한 것이기 때문이다. 즉 `X(Nf(f))`에서 `f`를 추정된 인자로 바꾼 것이 되는데, 문제는 `Nf(f)`가 `(cls z) => N(f(z))`로 정의되었다는 것이다. `z`는 여기에서 기원한다.

이는 꽤 오래 전부터 문제가 되었는데, #3 역시 이것에 관한 이슈이다. 지금 저 `z`를 `x`로 바꾸는 방법은 `as` 구문이나 `id`를 쓰는 것밖에 없다.

**Comment by logico-philosophical** [comment]
파싱 오류 아님 ㅇㅇ
